name: dico
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  lucide_icons: ^0.257.0
  shared_preferences: ^2.3.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  file_picker: ^8.0.3
  flutter_file_dialog: ^3.0.2
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
